### ISSUE TITLE
Include parameters types from Wowpedia for global functions

### ISSUE THREAD

**Issue by Ellypse** [Ellypse/IntelliJ-IDEA-Lua-IDE-WoW-API#9]
The generated files would benefit a lot from also scraping the parameter types and generating the documentation for them.
They are listed in the Arguments section (see this example https://wow.gamepedia.com/API_AbandonSkill).

**Comment by vendethiel** [comment]
Maybe someday those will be documented in the same format as the C_ globals...

**Comment by vendethiel** [comment]
Is there a way to get the text for all these without having to DDoS gamepedia? (I know that's how it works currently, I just wonder if there's a better way)

**Comment by Ketho** [comment]
> Maybe someday those will be documented in the same format as the C_ globals...

Yuyuli tried to convert them from Resike's [Sublime snippets](https://github.com/Resike/WoWDevelopment/tree/master/Reference/API%20Reference) to [Blizzard style API docs](https://gist.github.com/Ketho/773ca5313ea61a23a1bb882d40e5f4c5), but otherwise it probably is a lot of work to document them in the same format

Stanzilla and Nebula are using it now for their [Selene](https://github.com/Kampfkarren/selene) parser I think
https://github.com/nebularg/wow-selene-parser

> Is there a way to get the text for all these without having to DDoS gamepedia? (I know that's how it works currently, I just wonder if there's a better way)

Yeah, you can export them from the "API_functions" category to XML
https://wow.gamepedia.com/Special:Export

**Comment by Ellypse** [comment]
I have found that the remaining opened PR had that and it's now merge. (I probably should have checked before creating the ticket, sorry). The latest commit on master has a version with the argument type annotation :)

On a side not, Stanzilla contacted me on the parser, it's look really interesting. I will keep a close eye on it :D
